# Generated by Django 3.1.1 on 2020-09-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fIndustry', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='firstName',
        ),
        migrations.AddField(
            model_name='person',
            name='surname',
            field=models.CharField(default='null', max_length=80),
        ),
    ]
