# Generated by Django 3.1.1 on 2020-09-24 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fIndustry', '0002_auto_20200922_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdetails',
            name='CHITNumber',
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fIndustry.person'),
        ),
        migrations.AddField(
            model_name='jobtalent',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fIndustry.job'),
        ),
        migrations.AddField(
            model_name='jobtalent',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fIndustry.person'),
        ),
        migrations.AddField(
            model_name='talent',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fIndustry.person'),
        ),
    ]
