# Generated by Django 3.1.1 on 2020-09-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fIndustry', '0004_person_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CHITNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CHITNo', models.IntegerField(default=0)),
            ],
        ),
    ]
