# Generated by Django 3.1.1 on 2020-09-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fIndustry', '0005_chitnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=254),
        ),
    ]
